### PR TITLE
team/morning_afternoon/feature/CombatSystemUpgrade

### PR DESCRIPTION
**Pull request by Coakim**
Health and stamina bars now follows player and added a fixed update timer for health and stamina draining

### CODE REVIEW

**Comment by DPrivalov** [comment]
Just to check, are u moving the character with transform changes? or by changing sprite position?

**Comment by Coakim** [comment]
> Just to check, are u moving the character with transform changes? or by changing sprite position?

When moving the character I was chaning both transform and sprite positions , and the stat bars just by changing the sprite positions

**Comment by DPrivalov** [comment]
Transform is updating sprite positions for the same entity. So no need to change character sprite position if you are using transform for this entity

**Comment by Coakim** [comment]
> Transform is updating sprite positions for the same entity. So no need to change character sprite position if you are using transform for this entity

Oh , didn't know that ... thanks for letting me know , will remove the sprite position updates then

**Comment by Coakim** [comment]
> Just to check, are u moving the character with transform changes? or by changing sprite position?

Okay , I have a question regarding the sprite and transform positions. Is it better to use transform component for chaning the position of sprites in general?  Currently I only used transform component with character position changes , and I just changed sprite positions for my crosshair sprites and health and stamina bar sprites

**Comment by DPrivalov** [comment]
> > Just to check, are u moving the character with transform changes? or by changing sprite position?
> 
> Okay , I have a question regarding the sprite and transform positions. Is it better to use transform component for chaning the position of sprites in general? Currently I only used transform component with character position changes , and I just changed sprite positions for my crosshair sprites and health and stamina bar sprites

Let's discuss it during today's call. (question can be: when should we use transform and when we can change sprite position instead)
In short it's really dependent on your game design. I think other sprites can get their position from character and have some offsets, so there is no need to have multiple transform components.

**Review by DamjanTM — APPROVED** [review]
looks good

**Pull request merged**
